### ISSUE TITLE
Corrections on `jsp_intro_quiz.html` Solution

### ISSUE THREAD

**Issue by KidusMT** [bayartsogt-ya/wap-my-lab-page#1]
Solutions for [this ](https://github.com/bayartsogt-ya/wap-my-lab-page/blob/main/labs/jsp_intro_quiz.html) 

> 
            Give an example of a JSP comment and show how it will look in the JSP servlet. 
            Answer: <%-- comment --%> => out.print(html comment string)
    
I think would be like this: 
`ignored on translation phase, since its a jsp comment and will be removed on translation to java file.`

[Some reference for my solution](https://sites.google.com/site/sureshdevang/jsp-comment-vs-html-comment)

![image](https://user-images.githubusercontent.com/18373774/118080015-ea1dba00-b37e-11eb-8e3d-4609b30ef389.png)

And THank you for the great resources you have in your repo! Appreciate your works!

**Comment by bayartsogt-ya** [comment]
Thank you for your help.
Just changed it accordingly. => [Can you check it again?](https://github.com/bayartsogt-ya/wap-my-lab-page/blob/main/labs/jsp_intro_quiz.html#L42)

**Comment by KidusMT** [comment]
Now it look perfect. 👍🏼
